### ISSUE TITLE
Ajuda para executar o "start"

### ISSUE THREAD

**Issue by neocite** [agutoli/react-simple-boilerplate#1]
Blza? Cara estava pensando em usar o seu projeto como referência estrutural para um novo projeto que estou começando. Será que você consegue me ajudar? Quando tento executar o start (npm start) logo após o install, recebo a seguinte resposta:

`ERROR in ./src/app.js
Module build failed: SyntaxError: Unexpected token (10:12)

   8 | class App extends React.Component {
   9 |

> 10 |   propTypes = {
>      |             ^
>   11 |     children: PropTypes.element
>   12 |   };
>   13 |

 @ multi app
webpack: bundle is now VALID.`

Tem alguma idéia do que pode ser?

**Comment by agutoli** [comment]
Olá @neocite , claro que posso ajudá-lo, vou remover o node_modules aqui e reinstalar tudo pra ver se consigo pegar o mesmo erro... mas acredito que tem relação com o módulo `transform-class-properties` do babel

**Comment by agutoli** [comment]
@neocite , removi o node_modules e reinstalei tudo, parece que está funcionando bem... vc consegue fazer este teste? a única coisa que atualizei foi um decorator, que não tem relação com este problema... 

é legal vc ter um node >= `v5.2.0` e npm >= `3.8.0`

valeu!!

**Comment by neocite** [comment]
Oh velho valeu mesmo...fiz o procedimento mas continua não rolando...vou continuar na caça por aqui...se tiver mais alguma luz, por favor, me fale. Agora sim estou com o node 5.3 e NPM 3.3.12.

**Comment by neocite** [comment]
Descobri! Faltava "apenas" o .babelrc no diretorio que fiz o clone (cagada toda minha)...valeu pela atenção :)
